#!/bin/bash

# \b ensures we match the whole word "mi-caffeine-flag"
CURR_STATE=$(pgrep -f "mi-caffeine-flag.sh")

if [[ -z $CURR_STATE ]] ; then
    # Start the flag normally. Your loop script will see this process.
    mi-caffeine-flag.sh & disown

    # INSTANT RESPONSIVENESS: Kill swayidle right now so the bar lights up instantly
    pkill -9 swayidle

    notify-send "Caffeine" "System will stay awake"
else
    # This will now only contain the PID of the flag
    kill $CURR_STATE

    notify-send "Caffeine" "Idle timers restored"
fi
